"""Add 'birthdate' column in database

Revision ID: 965263e2909d
Revises: d06b0384fac0
Create Date: 2020-06-27 10:51:05.602202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965263e2909d'
down_revision = 'd06b0384fac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('birthdate', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_employees_birthdate'), 'employees', ['birthdate'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_birthdate'), table_name='employees')
    op.drop_column('employees', 'birthdate')
    # ### end Alembic commands ###
